[2025-09-16T00:15:18.588+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:15:18.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:15:18.619+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:15:18.612+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:15:18.644+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:15:18.641+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:15:18.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:15:18.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.205 seconds
[2025-09-16T00:15:48.914+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:15:48.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:15:48.918+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:15:48.917+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:15:48.927+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:15:48.924+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:15:48.928+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:15:48.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.108 seconds
[2025-09-16T00:16:19.143+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:16:19.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:16:19.158+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:16:19.156+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:16:19.178+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:16:19.173+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:16:19.180+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:16:19.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.133 seconds
[2025-09-16T00:16:49.434+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:16:49.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:16:49.446+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:16:49.445+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:16:49.474+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:16:49.460+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:16:49.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:16:49.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.162 seconds
[2025-09-16T00:17:14.410+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:17:14.412+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:17:14.415+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:17:14.415+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:17:14.441+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:17:14.430+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:17:14.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:17:14.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.079 seconds
[2025-09-16T00:17:44.673+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:17:44.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:17:44.676+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:17:44.676+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:17:44.684+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:17:44.682+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:17:44.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:17:44.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.051 seconds
[2025-09-16T00:18:14.876+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:18:14.877+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:18:14.880+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:18:14.879+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:18:14.888+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:18:14.885+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:18:14.888+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:18:14.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.050 seconds
[2025-09-16T00:18:45.137+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:18:45.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:18:45.146+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:18:45.145+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:18:45.160+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:18:45.156+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:18:45.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:18:45.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.108 seconds
[2025-09-16T00:19:15.334+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:19:15.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:19:15.338+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:19:15.338+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:19:15.347+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:19:15.344+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:19:15.348+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:19:15.385+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.059 seconds
[2025-09-16T00:19:45.556+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:19:45.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:19:45.560+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:19:45.559+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:19:45.568+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:19:45.566+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:19:45.569+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:19:45.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.053 seconds
[2025-09-16T00:20:15.834+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:20:15.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:20:15.838+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:20:15.837+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:20:15.847+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:20:15.843+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:20:15.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:20:15.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.053 seconds
[2025-09-16T00:20:46.039+0000] {processor.py:161} INFO - Started process (PID=203) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:20:46.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:20:46.043+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:20:46.043+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:20:46.053+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:20:46.050+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:20:46.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:20:46.087+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.057 seconds
[2025-09-16T00:21:16.272+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:21:16.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:21:16.275+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:21:16.275+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:21:16.284+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:21:16.281+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:21:16.285+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:21:16.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.049 seconds
[2025-09-16T00:21:46.475+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:21:46.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:21:46.479+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:21:46.478+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:21:46.486+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:21:46.484+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:21:46.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:21:46.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.050 seconds
[2025-09-16T00:22:16.713+0000] {processor.py:161} INFO - Started process (PID=218) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:22:16.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:22:16.717+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:22:16.716+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:22:16.725+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:22:16.722+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:22:16.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:22:16.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.050 seconds
[2025-09-16T00:22:46.937+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:22:46.938+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:22:46.941+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:22:46.940+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:22:46.950+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:22:46.947+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:22:46.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:22:46.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.059 seconds
[2025-09-16T00:23:17.126+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:23:17.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:23:17.130+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:23:17.130+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:23:17.138+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:23:17.136+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:23:17.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:23:17.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.052 seconds
[2025-09-16T00:23:47.384+0000] {processor.py:161} INFO - Started process (PID=239) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:23:47.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:23:47.388+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:23:47.388+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:23:47.396+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:23:47.394+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:23:47.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:23:47.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.051 seconds
[2025-09-16T00:24:17.727+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:24:17.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:24:17.732+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:24:17.731+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:24:17.772+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:24:17.762+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:24:17.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:24:17.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.214 seconds
[2025-09-16T00:24:47.955+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:24:47.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:24:47.959+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:24:47.959+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:24:47.968+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:24:47.965+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:24:47.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:24:48.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.121 seconds
[2025-09-16T00:25:18.340+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:25:18.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:25:18.355+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:25:18.353+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:25:18.375+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:25:18.369+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:25:18.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:25:18.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.144 seconds
[2025-09-16T00:25:48.586+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:25:48.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:25:48.596+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:25:48.594+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:25:48.609+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:25:48.605+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:25:48.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:25:48.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.121 seconds
[2025-09-16T00:26:18.831+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:26:18.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:26:18.836+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:26:18.836+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:26:18.843+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:26:18.841+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:26:18.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:26:18.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.161 seconds
[2025-09-16T00:26:49.078+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:26:49.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:26:49.082+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:26:49.081+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:26:49.095+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:26:49.091+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:26:49.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:26:49.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.068 seconds
[2025-09-16T00:27:19.397+0000] {processor.py:161} INFO - Started process (PID=315) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:27:19.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:27:19.402+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:27:19.402+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:27:19.414+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:27:19.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:27:19.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:27:19.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.071 seconds
[2025-09-16T00:27:49.641+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:27:49.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:27:49.645+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:27:49.645+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:27:49.667+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:27:49.663+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:27:49.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:27:49.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.224 seconds
[2025-09-16T00:28:20.082+0000] {processor.py:161} INFO - Started process (PID=363) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:28:20.086+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:28:20.089+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:28:20.089+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:28:20.103+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:28:20.094+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:28:20.104+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:28:20.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.395 seconds
[2025-09-16T00:28:50.800+0000] {processor.py:161} INFO - Started process (PID=368) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:28:50.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:28:50.804+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:28:50.804+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:28:50.813+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:28:50.811+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T00:28:50.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:28:50.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.059 seconds
[2025-09-16T00:29:20.987+0000] {processor.py:161} INFO - Started process (PID=373) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:29:20.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:29:20.992+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:29:20.992+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:29:21.000+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:29:20.998+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-apache-spark:5.3.2` needs Apache Airflow 2.10.0+
[2025-09-16T00:29:21.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:29:21.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.058 seconds
[2025-09-16T00:29:51.201+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:29:51.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:29:51.205+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:29:51.204+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:29:51.213+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:29:51.211+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-apache-spark:5.3.2` needs Apache Airflow 2.10.0+
[2025-09-16T00:29:51.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:29:51.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.056 seconds
[2025-09-16T00:30:21.417+0000] {processor.py:161} INFO - Started process (PID=383) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:30:21.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:30:21.422+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:30:21.421+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:30:21.430+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:30:21.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-apache-spark:5.3.2` needs Apache Airflow 2.10.0+
[2025-09-16T00:30:21.431+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:30:21.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.057 seconds
[2025-09-16T00:30:51.629+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:30:51.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:30:51.633+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:30:51.632+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:30:51.641+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:30:51.639+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-apache-spark:5.3.2` needs Apache Airflow 2.10.0+
[2025-09-16T00:30:51.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:30:51.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.060 seconds
[2025-09-16T00:31:21.852+0000] {processor.py:161} INFO - Started process (PID=393) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:31:21.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:31:21.856+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:31:21.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:31:21.864+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:31:21.862+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-apache-spark:5.3.2` needs Apache Airflow 2.10.0+
[2025-09-16T00:31:21.866+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:31:21.895+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.059 seconds
[2025-09-16T00:31:52.052+0000] {processor.py:161} INFO - Started process (PID=398) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:31:52.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:31:52.056+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:31:52.055+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:31:52.064+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:31:52.061+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-apache-spark:5.3.2` needs Apache Airflow 2.10.0+
[2025-09-16T00:31:52.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:31:52.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.059 seconds
[2025-09-16T00:32:22.307+0000] {processor.py:161} INFO - Started process (PID=403) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:32:22.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:32:22.312+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:32:22.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:32:22.322+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:32:22.319+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-apache-spark:5.3.2` needs Apache Airflow 2.10.0+
[2025-09-16T00:32:22.323+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:32:22.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.068 seconds
[2025-09-16T00:32:52.535+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:32:52.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:32:52.539+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:32:52.539+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:32:52.547+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:32:52.545+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-apache-spark:5.3.2` needs Apache Airflow 2.10.0+
[2025-09-16T00:32:52.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:32:52.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.057 seconds
[2025-09-16T00:33:22.824+0000] {processor.py:161} INFO - Started process (PID=413) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:33:22.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T00:33:22.828+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:33:22.827+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:33:22.836+0000] {logging_mixin.py:188} INFO - [2025-09-16T00:33:22.833+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-apache-spark:5.3.2` needs Apache Airflow 2.10.0+
[2025-09-16T00:33:22.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T00:33:22.867+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.060 seconds
[2025-09-16T01:28:42.016+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:28:42.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:28:42.021+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:28:42.020+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:28:42.034+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:28:42.031+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:28:42.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:28:42.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.062 seconds
[2025-09-16T01:29:12.263+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:29:12.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:29:12.268+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:29:12.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:29:12.277+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:29:12.273+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:29:12.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:29:12.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.061 seconds
[2025-09-16T01:29:42.471+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:29:42.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:29:42.476+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:29:42.475+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:29:42.485+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:29:42.482+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:29:42.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:29:42.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.055 seconds
[2025-09-16T01:30:12.734+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:30:12.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:30:12.738+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:30:12.737+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:30:12.746+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:30:12.744+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:30:12.747+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:30:12.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.052 seconds
[2025-09-16T01:30:42.942+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:30:42.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:30:42.946+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:30:42.945+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:30:42.954+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:30:42.952+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:30:42.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:30:42.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.053 seconds
[2025-09-16T01:31:13.207+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:31:13.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:31:13.216+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:31:13.216+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:31:13.227+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:31:13.224+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:31:13.228+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:31:13.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.080 seconds
[2025-09-16T01:31:43.524+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:31:43.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:31:43.529+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:31:43.528+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:31:43.539+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:31:43.536+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:31:43.541+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:31:43.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.066 seconds
[2025-09-16T01:32:13.752+0000] {processor.py:161} INFO - Started process (PID=203) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:32:13.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:32:13.759+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:32:13.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:32:13.801+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:32:13.767+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:32:13.805+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:32:13.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.115 seconds
[2025-09-16T01:32:44.057+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:32:44.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:32:44.063+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:32:44.062+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:32:44.073+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:32:44.070+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:32:44.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:32:44.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.071 seconds
[2025-09-16T01:33:14.280+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:33:14.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:33:14.284+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:33:14.284+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:33:14.293+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:33:14.290+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:33:14.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:33:14.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.056 seconds
[2025-09-16T01:33:44.590+0000] {processor.py:161} INFO - Started process (PID=218) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:33:44.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:33:44.595+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:33:44.594+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:33:44.604+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:33:44.602+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:33:44.605+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:33:44.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.059 seconds
[2025-09-16T01:34:14.818+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:34:14.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:34:14.822+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:34:14.822+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:34:14.831+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:34:14.828+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:34:14.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:34:14.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.056 seconds
[2025-09-16T01:34:45.412+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:34:45.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:34:45.428+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:34:45.426+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:34:45.443+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:34:45.440+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:34:45.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:34:45.493+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.096 seconds
[2025-09-16T01:35:15.635+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:35:15.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:35:15.639+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:35:15.638+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:35:15.649+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:35:15.646+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:35:15.650+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:35:15.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.067 seconds
[2025-09-16T01:35:45.965+0000] {processor.py:161} INFO - Started process (PID=238) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:35:45.967+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:35:45.974+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:35:45.973+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:35:45.987+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:35:45.984+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:35:45.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:35:46.022+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.074 seconds
[2025-09-16T01:36:16.143+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:36:16.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:36:16.147+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:36:16.146+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:36:16.155+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:36:16.153+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:36:16.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:36:16.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.055 seconds
[2025-09-16T01:36:46.412+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:36:46.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:36:46.416+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:36:46.415+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:36:46.424+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:36:46.421+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:36:46.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:36:46.456+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.054 seconds
[2025-09-16T01:37:16.620+0000] {processor.py:161} INFO - Started process (PID=253) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:37:16.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:37:16.624+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:37:16.623+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:37:16.632+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:37:16.630+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:37:16.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:37:16.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.052 seconds
[2025-09-16T01:37:46.830+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:37:46.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:37:46.834+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:37:46.834+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:37:46.843+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:37:46.840+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:37:46.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:37:46.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.058 seconds
[2025-09-16T01:38:17.112+0000] {processor.py:161} INFO - Started process (PID=263) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:38:17.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:38:17.116+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:38:17.116+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:38:17.125+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:38:17.122+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:38:17.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:38:17.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.056 seconds
[2025-09-16T01:38:47.393+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:38:47.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:38:47.403+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:38:47.402+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:38:47.411+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:38:47.409+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:38:47.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:38:47.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.062 seconds
[2025-09-16T01:39:17.583+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:39:17.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:39:17.588+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:39:17.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:39:17.596+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:39:17.594+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:39:17.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:39:17.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.054 seconds
[2025-09-16T01:39:47.800+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:39:47.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:39:47.805+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:39:47.805+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:39:47.815+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:39:47.813+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:39:47.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:39:47.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.054 seconds
[2025-09-16T01:40:18.005+0000] {processor.py:161} INFO - Started process (PID=283) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:40:18.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:40:18.010+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:40:18.009+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:40:18.021+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:40:18.018+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:40:18.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:40:18.080+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.085 seconds
[2025-09-16T01:40:48.255+0000] {processor.py:161} INFO - Started process (PID=288) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:40:48.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:40:48.260+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:40:48.259+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:40:48.268+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:40:48.266+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:40:48.269+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:40:48.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.057 seconds
[2025-09-16T01:41:18.550+0000] {processor.py:161} INFO - Started process (PID=293) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:41:18.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:41:18.567+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:41:18.564+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:41:18.580+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:41:18.576+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:41:18.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:41:18.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.124 seconds
[2025-09-16T01:41:48.872+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:41:48.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:41:48.881+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:41:48.881+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:41:48.897+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:41:48.892+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:41:48.898+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:41:48.945+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.129 seconds
[2025-09-16T01:42:19.129+0000] {processor.py:161} INFO - Started process (PID=303) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:42:19.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:42:19.133+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:42:19.133+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:42:19.146+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:42:19.140+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:42:19.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:42:19.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.087 seconds
[2025-09-16T01:42:49.375+0000] {processor.py:161} INFO - Started process (PID=308) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:42:49.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:42:49.379+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:42:49.379+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:42:49.396+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:42:49.388+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:42:49.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:42:49.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.091 seconds
[2025-09-16T01:43:19.576+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:43:19.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:43:19.580+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:43:19.579+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:43:19.588+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:43:19.586+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:43:19.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:43:19.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.063 seconds
[2025-09-16T01:43:49.802+0000] {processor.py:161} INFO - Started process (PID=318) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:43:49.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:43:49.806+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:43:49.806+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:43:49.814+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:43:49.812+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:43:49.815+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:43:49.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.050 seconds
[2025-09-16T01:44:20.013+0000] {processor.py:161} INFO - Started process (PID=323) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:44:20.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:44:20.017+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:44:20.017+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:44:20.026+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:44:20.023+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:44:20.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:44:20.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.076 seconds
[2025-09-16T01:44:50.244+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:44:50.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:44:50.248+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:44:50.248+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:44:50.256+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:44:50.253+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:44:50.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:44:50.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.051 seconds
[2025-09-16T01:45:20.476+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:45:20.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:45:20.479+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:45:20.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:45:20.487+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:45:20.485+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:45:20.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:45:20.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.050 seconds
[2025-09-16T01:45:50.676+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:45:50.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:45:50.680+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:45:50.680+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:45:50.688+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:45:50.686+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:45:50.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:45:50.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.050 seconds
[2025-09-16T01:46:20.883+0000] {processor.py:161} INFO - Started process (PID=343) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:46:20.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:46:20.887+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:46:20.887+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:46:20.895+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:46:20.893+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:46:20.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:46:20.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.051 seconds
[2025-09-16T01:46:51.105+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:46:51.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:46:51.109+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:46:51.108+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:46:51.117+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:46:51.114+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:46:51.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:46:51.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.050 seconds
[2025-09-16T01:47:21.311+0000] {processor.py:161} INFO - Started process (PID=353) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:47:21.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:47:21.316+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:47:21.315+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:47:21.324+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:47:21.322+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:47:21.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:47:21.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.057 seconds
[2025-09-16T01:47:51.539+0000] {processor.py:161} INFO - Started process (PID=358) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:47:51.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:47:51.543+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:47:51.543+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:47:51.552+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:47:51.549+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:47:51.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:47:51.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.051 seconds
[2025-09-16T01:48:21.738+0000] {processor.py:161} INFO - Started process (PID=363) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:48:21.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:48:21.742+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:48:21.741+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:48:21.751+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:48:21.748+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:48:21.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:48:21.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.051 seconds
[2025-09-16T01:48:51.985+0000] {processor.py:161} INFO - Started process (PID=368) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:48:51.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:48:51.989+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:48:51.989+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:48:51.997+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:48:51.994+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:48:51.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:48:52.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.056 seconds
[2025-09-16T01:49:22.187+0000] {processor.py:161} INFO - Started process (PID=373) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:49:22.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:49:22.192+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:49:22.191+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:49:22.200+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:49:22.197+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:49:22.201+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:49:22.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.057 seconds
[2025-09-16T01:49:52.418+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:49:52.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:49:52.422+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:49:52.421+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:49:52.430+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:49:52.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:49:52.431+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:49:52.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.052 seconds
[2025-09-16T01:50:22.651+0000] {processor.py:161} INFO - Started process (PID=383) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:50:22.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:50:22.655+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:50:22.654+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:50:22.665+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:50:22.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:50:22.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:50:22.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.055 seconds
[2025-09-16T01:50:52.850+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:50:52.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:50:52.854+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:50:52.854+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:50:52.862+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:50:52.860+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:50:52.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:50:52.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.057 seconds
[2025-09-16T01:51:23.084+0000] {processor.py:161} INFO - Started process (PID=393) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:51:23.085+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:51:23.088+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:51:23.088+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:51:23.096+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:51:23.094+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:51:23.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:51:23.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.051 seconds
[2025-09-16T01:51:53.291+0000] {processor.py:161} INFO - Started process (PID=398) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:51:53.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:51:53.295+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:51:53.294+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:51:53.302+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:51:53.300+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:51:53.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:51:53.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.052 seconds
[2025-09-16T01:52:23.505+0000] {processor.py:161} INFO - Started process (PID=403) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:52:23.506+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:52:23.509+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:52:23.508+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:52:23.517+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:52:23.514+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:52:23.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:52:23.547+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.052 seconds
[2025-09-16T01:52:53.715+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:52:53.717+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:52:53.720+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:52:53.720+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:52:53.728+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:52:53.726+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:52:53.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:52:53.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.052 seconds
[2025-09-16T01:53:24.013+0000] {processor.py:161} INFO - Started process (PID=413) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:53:24.016+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:53:24.022+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:53:24.021+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:53:24.035+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:53:24.031+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:53:24.038+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:53:24.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.114 seconds
[2025-09-16T01:53:54.201+0000] {processor.py:161} INFO - Started process (PID=418) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:53:54.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:53:54.206+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:53:54.206+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:53:54.215+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:53:54.212+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:53:54.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:53:54.246+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.055 seconds
[2025-09-16T01:54:24.474+0000] {processor.py:161} INFO - Started process (PID=423) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:54:24.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:54:24.491+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:54:24.487+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:54:24.522+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:54:24.515+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:54:24.524+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:54:24.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.147 seconds
[2025-09-16T01:54:54.911+0000] {processor.py:161} INFO - Started process (PID=428) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:54:54.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:54:54.918+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:54:54.918+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:54:54.929+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:54:54.926+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:54:54.930+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:54:54.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.095 seconds
[2025-09-16T01:55:25.100+0000] {processor.py:161} INFO - Started process (PID=433) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:55:25.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:55:25.105+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:55:25.105+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:55:25.113+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:55:25.111+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:55:25.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:55:25.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.064 seconds
[2025-09-16T01:55:55.573+0000] {processor.py:161} INFO - Started process (PID=438) to work on /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:55:55.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aggregation_pipeline_dag.py for tasks to queue
[2025-09-16T01:55:55.633+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:55:55.626+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:55:55.652+0000] {logging_mixin.py:188} INFO - [2025-09-16T01:55:55.649+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aggregation_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aggregation_pipeline_dag.py", line 3, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2025-09-16T01:55:55.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aggregation_pipeline_dag.py
[2025-09-16T01:55:55.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aggregation_pipeline_dag.py took 0.383 seconds
